vich_uploader:
    db_driver: orm
    mappings:
        event:
            uri_prefix: /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true

